# =============================================================
# Qualys-SDP Automation Setup Script
# Creates a Windows Scheduled Task from Config\.env settings
#
# Supported Frequencies:
#   Daily   - runs every day at AUTO_RUN_TIME
#   Weekly  - runs on AUTO_RUN_DAYS at AUTO_RUN_TIME
#   Monthly - runs on the Nth occurrence of AUTO_RUN_DAYS
#             in the month (controlled by AUTO_RUN_WEEK_OF_MONTH)
#             e.g. AUTO_RUN_DAYS=Friday, AUTO_RUN_WEEK_OF_MONTH=1 → 1st Friday
# =============================================================

# 1. Determine Project Root (two levels up from scripts/Slave)
$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$projectRoot = Split-Path -Parent (Split-Path -Parent $scriptDir)
$envPath     = Join-Path $projectRoot "Config\.env"

# 2. Load .env file
function Import-Env {
    param($Path)
    if (Test-Path $Path) {
        Get-Content $Path | ForEach-Object {
            if ($_ -match "^\s*([^#\s][^=]*)\s*=\s*['""]?(.*?)['""]?\s*$") {
                Set-Variable -Name "ENV_$($matches[1].Trim())" -Value $matches[2].Trim() -Scope Script -Force
            }
        }
    }
}
Import-Env -Path $envPath

# 3. Paths & Defaults
$venvPython  = Join-Path $projectRoot ".venv\Scripts\python.exe"
$masterScript = Join-Path $projectRoot "scripts\Master\Master.py"
$taskName    = "Qualys-SDP-Integration"
$wrapperPath = Join-Path $projectRoot "scripts\Slave\_run_check.ps1"

$freq        = if ($Script:ENV_AUTO_RUN_FREQUENCY) { $Script:ENV_AUTO_RUN_FREQUENCY } else { "Daily" }
$time        = if ($Script:ENV_AUTO_RUN_TIME)       { $Script:ENV_AUTO_RUN_TIME }      else { "09:00" }
$daysRaw     = if ($Script:ENV_AUTO_RUN_DAYS)       { $Script:ENV_AUTO_RUN_DAYS }      else { "Monday" }
$weekOfMonth = if ($Script:ENV_AUTO_RUN_WEEK_OF_MONTH) { $Script:ENV_AUTO_RUN_WEEK_OF_MONTH } else { "1" }

$daysArray = $daysRaw.Split(",") | ForEach-Object { $_.Trim() }

# 4. Validate paths
if (!(Test-Path $venvPython)) {
    Write-Error "Virtual environment not found. Run setup_env.ps1 first."
    exit 1
}
if (!(Test-Path $masterScript)) {
    Write-Error "Master script not found at $masterScript."
    exit 1
}

Write-Host "=================================================" -ForegroundColor Cyan
Write-Host "      Qualys-ME Automation Setup (Windows)       " -ForegroundColor Cyan
Write-Host "=================================================" -ForegroundColor Cyan

# 5. Build trigger & action based on frequency
try {
    if ($freq -eq "Daily") {
        $trigger   = New-ScheduledTaskTrigger -Daily -At $time
        $schedDesc = "Every day at $time"
        $action    = New-ScheduledTaskAction -Execute $venvPython `
                        -Argument """$masterScript""" `
                        -WorkingDirectory $projectRoot

    } elseif ($freq -eq "Weekly") {
        $trigger   = New-ScheduledTaskTrigger -Weekly -At $time -DaysOfWeek $daysArray
        $schedDesc = "Every [$daysRaw] at $time"
        $action    = New-ScheduledTaskAction -Execute $venvPython `
                        -Argument """$masterScript""" `
                        -WorkingDirectory $projectRoot

    } elseif ($freq -eq "Monthly") {
        # Windows Task Scheduler doesn't natively support "Nth weekday of month".
        # Solution: schedule Weekly on the chosen day, but wrap with a check script
        # that exits early if today is NOT the correct Nth occurrence.

        # Determine ordinal label
        $ordinal = switch ($weekOfMonth) {
            "1"    { "1st" }
            "2"    { "2nd" }
            "3"    { "3rd" }
            "4"    { "4th" }
            "Last" { "Last" }
            default { "${weekOfMonth}th" }
        }
        $schedDesc = "$ordinal $daysRaw of every month at $time"

        # Write the wrapper check script
        $wrapperContent = @"
# Auto-generated by automate_task.ps1 - DO NOT EDIT
# Runs the main script only on the $ordinal $daysRaw of the month
param()
`$target_day  = "$($daysArray[0])"
`$target_week = "$weekOfMonth"
`$today       = Get-Date

# Check: is today the correct day of the week?
if (`$today.DayOfWeek.ToString() -ne `$target_day) { exit 0 }

# Count which occurrence of this weekday we are in the month
`$occurrence = 0
for (`$d = 1; `$d -le `$today.Day; `$d++) {
    `$check = Get-Date -Year `$today.Year -Month `$today.Month -Day `$d
    if (`$check.DayOfWeek.ToString() -eq `$target_day) { `$occurrence++ }
}

# Handle "Last" week-of-month
if (`$target_week -eq "Last") {
    `$daysInMonth = [DateTime]::DaysInMonth(`$today.Year, `$today.Month)
    `$isLast = `$true
    for (`$d = `$today.Day + 1; `$d -le `$daysInMonth; `$d++) {
        `$check = Get-Date -Year `$today.Year -Month `$today.Month -Day `$d
        if (`$check.DayOfWeek.ToString() -eq `$target_day) { `$isLast = `$false; break }
    }
    if (-not `$isLast) { exit 0 }
} else {
    if (`$occurrence -ne [int]`$target_week) { exit 0 }
}

# Correct day — run the main script
& "$venvPython" "$masterScript"
"@
        Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding UTF8
        Write-Host "Wrapper script written to: $wrapperPath" -ForegroundColor Gray

        # Weekly trigger on the chosen day (the wrapper does the month-week check)
        $trigger = New-ScheduledTaskTrigger -Weekly -At $time -DaysOfWeek $daysArray
        $action  = New-ScheduledTaskAction -Execute "powershell.exe" `
                        -Argument "-NonInteractive -ExecutionPolicy Bypass -File ""$wrapperPath""" `
                        -WorkingDirectory $projectRoot

    } else {
        Write-Error "Unknown frequency: $freq. Use Daily, Weekly, or Monthly."
        exit 1
    }
} catch {
    Write-Error "Failed to create trigger: $_"
    Write-Host "For Weekly:  AUTO_RUN_DAYS = Monday, Friday ..."
    Write-Host "For Monthly: AUTO_RUN_DAYS = Friday, AUTO_RUN_WEEK_OF_MONTH = 1 (or 2,3,4,Last)"
    exit 1
}

# 6. Settings
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew

# 7. Register task
try {
    if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        Write-Host "Removing old task to update..." -ForegroundColor Gray
    }

    Register-ScheduledTask `
        -TaskName    $taskName `
        -Action      $action `
        -Trigger     $trigger `
        -Settings    $settings `
        -Description "Qualys to ServiceDesk Plus Integration | Schedule: $schedDesc"

    Write-Host "=================================================" -ForegroundColor Cyan
    Write-Host "        [SUCCESS] Automation Scheduled!          " -ForegroundColor Green
    Write-Host "=================================================" -ForegroundColor Cyan
    Write-Host "Task Name : $taskName"
    Write-Host "Schedule  : $schedDesc"
    Write-Host "=================================================" -ForegroundColor Cyan
    Write-Host "Manage this task in: taskschd.msc (Task Scheduler)" -ForegroundColor Yellow
} catch {
    Write-Error "FAILED: Run PowerShell as ADMINISTRATOR to register tasks."
}
